import type { UserRole, Permission } from '@/types';

export const ROLE_LABELS: Record<UserRole, string> = {
  SUPER_ADMIN: 'Super Admin',
  ORG_ADMIN: 'Organisation Admin',
  CENTRE_ADMIN: 'Centre Director',
  EDUCATOR: 'Educator',
  PARENT: 'Parent',
};

export const ROLE_COLORS: Record<UserRole, string> = {
  SUPER_ADMIN: '#7C3AED',
  ORG_ADMIN: '#2563EB',
  CENTRE_ADMIN: '#059669',
  EDUCATOR: '#D97706',
  PARENT: '#DC2626',
};

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  SUPER_ADMIN: [
    'children:read', 'children:write', 'children:delete',
    'families:read', 'families:write', 'families:delete',
    'enrolments:read', 'enrolments:write', 'enrolments:delete',
    'attendance:read', 'attendance:write',
    'dailyCare:read', 'dailyCare:write',
    'health:read', 'health:write',
    'medication:read', 'medication:write',
    'incidents:read', 'incidents:write', 'incidents:delete',
    'learning:read', 'learning:write', 'learning:delete',
    'media:read', 'media:write', 'media:delete',
    'messages:read', 'messages:write',
    'documents:read', 'documents:write', 'documents:delete',
    'consent:read', 'consent:write',
    'billing:read', 'billing:write',
    'reports:read',
    'settings:read', 'settings:write',
    'users:read', 'users:write', 'users:delete',
    'centres:read', 'centres:write',
  ],
  ORG_ADMIN: [
    'children:read', 'children:write',
    'families:read', 'families:write',
    'enrolments:read', 'enrolments:write',
    'attendance:read', 'attendance:write',
    'dailyCare:read', 'dailyCare:write',
    'health:read', 'health:write',
    'medication:read', 'medication:write',
    'incidents:read', 'incidents:write',
    'learning:read', 'learning:write',
    'media:read', 'media:write',
    'messages:read', 'messages:write',
    'documents:read', 'documents:write',
    'consent:read', 'consent:write',
    'billing:read', 'billing:write',
    'reports:read',
    'settings:read', 'settings:write',
    'users:read', 'users:write',
    'centres:read', 'centres:write',
  ],
  CENTRE_ADMIN: [
    'children:read', 'children:write',
    'families:read', 'families:write',
    'enrolments:read', 'enrolments:write',
    'attendance:read', 'attendance:write',
    'dailyCare:read', 'dailyCare:write',
    'health:read', 'health:write',
    'medication:read', 'medication:write',
    'incidents:read', 'incidents:write',
    'learning:read', 'learning:write',
    'media:read', 'media:write',
    'messages:read', 'messages:write',
    'documents:read', 'documents:write',
    'consent:read', 'consent:write',
    'billing:read', 'billing:write',
    'reports:read',
    'settings:read', 'settings:write',
    'users:read',
    'centres:read',
  ],
  EDUCATOR: [
    'children:read',
    'families:read',
    'attendance:read', 'attendance:write',
    'dailyCare:read', 'dailyCare:write',
    'health:read',
    'medication:read', 'medication:write',
    'incidents:read', 'incidents:write',
    'learning:read', 'learning:write',
    'media:read', 'media:write',
    'messages:read', 'messages:write',
    'documents:read',
    'consent:read',
  ],
  PARENT: [
    'children:read',
    'families:read',
    'attendance:read',
    'dailyCare:read',
    'health:read',
    'medication:read',
    'learning:read',
    'media:read',
    'messages:read', 'messages:write',
    'documents:read',
    'consent:read', 'consent:write',
    'billing:read',
  ],
};
